databases:
  - name: blog_contentful
    databaseName: blog_contentful
    user: blog_contentful

services:
  - type: web
    name: blog_contentful
    runtime: python
    rootDir: blog_contentful
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn blog_contentful.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog_contentful
          property: connectionString
